"""Initial migration

Revision ID: 5d68d84ca285
Revises:
Create Date: 2025-11-08 15:03:57.333862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5d68d84ca285"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("OPEN", "IN_PROGRESS", "CLOSED", name="incidentstatus"),
            nullable=False,
        ),
        sa.Column(
            "source",
            postgresql.ENUM("OPERATOR", "MONITORING", "PARTNER", name="incidentsource"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_table("incidents")
    postgresql.ENUM(name="incidentsource").drop(op.get_bind())
    postgresql.ENUM(name="incidentstatus").drop(op.get_bind())
    # ### end Alembic commands ###
